# Generated by Django 3.1.4 on 2024-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='yoshi',
            field=models.CharField(max_length=20),
        ),
    ]
